/**
 * The box tool interacts with everything by turning them in 📦
 * It has a fixed cost of -100 score per use
 */

/**
 * The flat iron tool interacts with the following predefined emojis. It may result in positive or negative score change.
 * Some special items may be destroyed when ironed.
 */

const ironToolTransforms = [
  { input: "👕", output: "🧺", score: 100 },
  { input: "👗", output: "🧺", score: 100 },
  { input: "👖", output: "🧺", score: 100 },
  { input: "👘", output: "🧺", score: 100 },
  { input: "👔", output: "🧺", score: 100 },
  { input: "👙", output: "🧺", score: 100 },
  { input: "🧥", output: "🧺", score: 100 },
  { input: "👚", output: "🧺", score: 100 },
  { input: "🩳", output: "🧺", score: 100 },
  { input: "🧦", output: "🧺", score: 100 },
  { input: "🧤", output: "🧺", score: 100 },
  { input: "🧣", output: "🧺", score: 100 },
  { input: "🥻", output: "🧺", score: 100 },
  { input: "🩱", output: "🧺", score: 100 },
  { input: "🩲", output: "🧺", score: 100 },
  { input: "🥼", output: "🧺", score: 100 },
  { input: "🦺", output: "🧺", score: 100 },
  { input: "🥋", output: "🧺", score: 100 },
  { input: "👰", output: "🧺", score: 100 },
  { input: "🤵", output: "🧺", score: 100 },
  { input: "🍓", output: "🍯", score: -100 },
  { input: "🍇", output: "🍷", score: -100 },
  { input: "🍅", output: "🥫", score: -100 },
  { input: "🍎", output: "🧃", score: -100 },
  { input: "🍑", output: "🍯", score: -100 },
  { input: "🍒", output: "🍯", score: -100 },
  { input: "🫐", output: "🍯", score: -100 },
  { input: "🥝", output: "🧃", score: -100 },
  { input: "🍐", output: "🧃", score: -100 },
  { input: "🍍", output: "🧃", score: -100 },
  { input: "🥭", output: "🍯", score: -100 },
  { input: "🍉", output: "💧", score: -100 },
  { input: "🍌", output: "🍮", score: -100 },
  { input: "🌽", output: "🍿", score: 100 },
  { input: "🥔", output: "🍟", score: 100 },
  { input: "🥓", output: "🍳", score: 100 },
  { input: "🥩", output: "🍳", score: 100 },
  { input: "🥚", output: "🍳", score: 100 },
  { input: "🧀", output: "🫠", score: 100 },
  { input: "🧈", output: "🫠", score: 100 },
  { input: "🍔", output: "💥", score: -300, destroyed: true },
  { input: "🍕", output: "🍕", score: 100 },
  { input: "🥪", output: "🥪", score: 100 },
  { input: " taco ", output: "💥", score: -300, destroyed: true },
  { input: "🌯", output: "💥", score: -300, destroyed: true },
  { input: "🍰", output: "🧁", score: -300 },
  { input: "🎂", output: "🧁", score: -300 },
  { input: "🧁", output: "💥", score: -300, destroyed: true },
  { input: "🍦", output: "💧", score: -300 },
  { input: "🍧", output: "💧", score: -300 },
  { input: "🍨", output: "💧", score: -300 },
  { input: "🍩", output: "🍪", score: -100 },
  { input: "🍪", output: "💥", score: -100, destroyed: true },
  { input: "🥨", output: "🍪", score: -100 },
  { input: "🍮", output: "💥", score: -300, destroyed: true },
  { input: "🍫", output: "🫠", score: -100 },
  { input: "🍬", output: "🫠", score: -100 },
  { input: "🍭", output: "🫠", score: -100 },
  { input: "🐱", output: "🙀", score: -300 },
  { input: "🐶", output: "🐕", score: -300 },
  { input: "🐹", output: "🐹", score: -300 },
  { input: "🐰", output: "🐰", score: -300 },
  { input: "🐭", output: "🐭", score: -300 },
  { input: "🦊", output: "🦊", score: -300 },
  { input: "🐻", output: "🐻", score: -300 },
  { input: "🐼", output: "🐼", score: -300 },
  { input: "🐨", output: "🐨", score: -300 },
  { input: "🐯", output: "🐯", score: -300 },
  { input: "🦁", output: "🦁", score: -300 },
  { input: "🐮", output: "🐮", score: -300 },
  { input: "🐷", output: "🐷", score: -300 },
  { input: "🐸", output: "🐸", score: -300 },
  { input: "🐵", output: "🐵", score: -300 },
  { input: "🐔", output: "🍗", score: -300 },
  { input: "🐧", output: "🐧", score: -300 },
  { input: "🐦", output: "🐦", score: -300 },
  { input: "🐤", output: "🐤", score: -300 },
  { input: "🦆", output: "🦆", score: -300 },
  { input: "🦅", output: "🦅", score: -300 },
  { input: "🦉", output: "🦉", score: -300 },
  { input: "🦇", output: "🦇", score: -300 },
  { input: "🐺", output: "🐺", score: -300 },
  { input: "🐗", output: "🐗", score: -300 },
  { input: "🐴", output: "🐴", score: -300 },
  { input: "🦄", output: "🦄", score: -300 },
  { input: "🦓", output: "🦓", score: -300 },
  { input: "🦒", output: "🦒", score: -300 },
  { input: "🐘", output: "🐘", score: -300 },
  { input: "🦏", output: "🦏", score: -300 },
  { input: "🦛", output: "🦛", score: -300 },
  { input: "🐁", output: "🐁", score: -300 },
  { input: "🐀", output: "🐀", score: 300 },
  { input: "🐿️", output: "🐿️", score: -300 },
  { input: "🦔", output: "🦔", score: -100 },
  { input: "🦦", output: "🦦", score: -300 },
  { input: "🦥", output: "🦥", score: -300 },
  { input: "🦘", output: "🦘", score: -300 },
  { input: "🦡", output: "🦡", score: -300 },
  { input: "🦃", output: "🍗", score: -300 },
  { input: "Swan", output: "🦢", score: -300 },
  { input: "🦩", output: "🦩", score: -300 },
  { input: "🕊️", output: "🕊️", score: -300 },
  { input: "🦜", output: "🦜", score: -300 },
  { input: "🦎", output: "🦎", score: -300 },
  { input: "🦖", output: "🦖", score: -300 },
  { input: "🦕", output: "🦕", score: -300 },
  { input: "🐳", output: "🐳", score: -300 },
  { input: "🐋", output: "🐋", score: -300 },
  { input: "🦈", output: "🦈", score: -300 },
  { input: "🐙", output: "🦑", score: -300 },
  { input: "🐡", output: "💥", score: -300, destroyed: true },
  { input: "🐠", output: "🐠", score: -300 },
  { input: "🐬", output: "🐬", score: -300 },
  { input: "🦀", output: "🦀", score: -100 },
  { input: "🦞", output: "🦞", score: -100 },
  { input: "🦐", output: "🦐", score: -100 },
  { input: "🦑", output: "🦑", score: -100 },
  { input: "🐝", output: "💥", score: -100, destroyed: true },
  { input: "🐛", output: "💥", score: -100, destroyed: true },
  { input: "🦋", output: "💥", score: -300, destroyed: true },
  { input: "🐌", output: "💥", score: -100, destroyed: true },
  { input: "🐞", output: "💥", score: -100, destroyed: true },
  { input: "🦂", output: "💥", score: 300, destroyed: true },
  { input: "🕷️", output: "💥", score: 300, destroyed: true },
  { input: "🦟", output: "💥", score: 300, destroyed: true },
  { input: "🦠", output: "💥", score: 300, destroyed: true },
  { input: "🧍", output: "🤕", score: -300 },
  { input: "👶", output: "🤕", score: -300 },
  { input: "👴", output: "🤕", score: -300 },
  { input: "👵", output: "🤕", score: -300 },
  { input: "👨", output: "🤕", score: -300 },
  { input: "👩", output: "🤕", score: -300 },
  { input: "👧", output: "🤕", score: -300 },
  { input: "👦", output: "🤕", score: -300 },
  { input: "👮", output: "🤕", score: -300 },
  { input: "👷", output: "🤕", score: -300 },
  { input: "💂", output: "🤕", score: -300 },
  { input: "🕵️", output: "🤕", score: -300 },
  { input: "🦸", output: "🤕", score: -300 },
  { input: "🦹", output: "🤕", score: -300 },
  { input: "🧙", output: "🤕", score: -300 },
  { input: "🧝", output: "🤕", score: -300 },
  { input: "🧛", output: "🤕", score: -300 },
  { input: "🧟", output: "🤕", score: -100 },
  { input: "🧜", output: "🤕", score: -300 },
  { input: "🧚", output: "🤕", score: -300 },
  { input: "👼", output: "🤕", score: -300 },
  { input: "🌻", output: "🥀", score: -100 },
  { input: "🌷", output: "🥀", score: -100 },
  { input: "🌹", output: "🥀", score: -100 },
  { input: "🌺", output: "🥀", score: -100 },
  { input: "🌸", output: "🥀", score: -100 },
  { input: "🌼", output: "🥀", score: -100 },
  { input: "🌱", output: "🥀", score: -100 },
  { input: "🌿", output: "🥀", score: -100 },
  { input: "🍀", output: "🥀", score: -100 },
  { input: "💐", output: "🥀", score: -100 },
  { input: "🌵", output: "🌵", score: -100 },
  { input: "🌲", output: "🌲", score: -100 },
  { input: "🌳", output: "🌳", score: -100 },
  { input: "🌴", output: "🌴", score: -100 },
  { input: "🍄", output: "💥", score: -100, destroyed: true },
  { input: "🧊", output: "💧", score: 100 },
  { input: "⛄", output: "💧", score: -100 },
  { input: "🏔️", output: "💧", score: -100 },
  { input: "🗻", output: "💧", score: -100 },
  { input: "🌋", output: "🔥", score: 300 },
  { input: "🎈", output: "💥", score: -100, destroyed: true },
  { input: "💵", output: "💸", score: 300 },
  { input: "🧧", output: "💵", score: 300 },
  { input: "📄", output: "📃", score: 100 },
  { input: "📜", output: "📃", score: 100 },
  { input: "🗺️", output: "📃", score: 100 },
  { input: "✉️", output: "📩", score: 100 },
  { input: "🕯️", output: "🫠", score: -100 },
  { input: "🖍️", output: "🫠", score: -100 },
  { input: "☕", output: "💨", score: 100, destroyed: true },
  { input: "🍵", output: "💨", score: 100, destroyed: true },
  { input: "♨️", output: "💨", score: 100, destroyed: true },
  { input: "🍼", output: "🥛", score: -100 },
  { input: "🥛", output: "🥛", score: -100 },
  { input: "🍷", output: "🍷", score: -100 },
  { input: "🍸", output: "🍸", score: -100 },
  { input: "🍹", output: "🍹", score: -100 },
  { input: "🍺", output: "🍺", score: -100 },
  { input: "🥤", output: "🥤", score: -100 },
  { input: "🥫", output: "💥", score: -300, destroyed: true },
  { input: "🍱", output: "💥", score: -300, destroyed: true },
  { input: "🥡", output: "💥", score: -300, destroyed: true },
  { input: "🌍", output: "🌍", score: -300 },
  { input: "🌎", output: "🌎", score: -300 },
  { input: "🌏", output: "🌏", score: -300 },
  { input: "🌡️", output: "💥", score: -300, destroyed: true },
  { input: "🧪", output: "💥", score: -300, destroyed: true },
  { input: "🧬", output: "💥", score: -300, destroyed: true },
  { input: "🧱", output: "🧱", score: -100 },
  { input: "🏠", output: "🏠", score: -300 },
  { input: "🏢", output: "🏢", score: -300 },
  { input: "🏕️", output: "⛺", score: 100 },
];
